### ISSUE TITLE
TypeScript compilation issue

### ISSUE THREAD

**Issue by Qwerios** [ozum/indexable-array#4]
Hello I'm trying to use `pg-structure` in one of my projects but when I try to compile it the tsc compiler borks at the types exposed by this module. Does this look at all familiar to you:

```
node_modules/indexable-array/dist/index.d.ts:76:90 - error TS2344: Type 'DK2' does not satisfy the constraint 'keyof I2'.
  Type 'DK' is not assignable to type 'keyof I2'.
    Type 'keyof I' is not assignable to type 'keyof I2'.
      Type 'string | number | symbol' is not assignable to type 'keyof I2'.
        Type 'string' is not assignable to type 'keyof I2'.
          Type 'string' is not assignable to type 'never'.
            Type 'keyof I' is not assignable to type 'never'.
              Type 'DK' is not assignable to type 'never'.
                Type 'DK2' is not assignable to type 'never'.
                  Type 'DK' is not assignable to type 'never'.
                    Type 'keyof I' is not assignable to type 'never'.
                      Type 'string | number | symbol' is not assignable to type 'never'.
                        Type 'string' is not assignable to type 'never'.

76     _copyMeta<I2 extends any, DK2 extends DK, OK2 extends OK>(source: IndexableArray<I2, DK2, OK2, any>): this;
```

At first I thought it could be a TypeScript 4 issue so I rolled back to 3.9.7 but that gives the same issue. I could not find a typescript version in your package.json to verify what you used. I've played around with the tsconfig.json settings with everything from es5 to es2019 to no avail. Any help would be appreciated

**Comment by Qwerios** [comment]
Through trial and error I have discovered that TypeScript 3.8.3 is that last version it compiles on. Any 3.9+ version will break compilation.

Checking the release notes this will likely be caused by the [stricter checks on intersections and optional properties](https://devblogs.microsoft.com/typescript/announcing-typescript-3-9/#stricter-checks-on-intersections-and-optional-properties). I've been bitten by that a few times as well :(

**Comment by jayarjo** [comment]
Same thing here. @Qwerios were you able to workaround it somehow?

**Comment by Qwerios** [comment]
@jayarjo I pinned my typescript version to 3.8.3 in package.json. I've not revisited the issue since

**Comment by jayarjo** [comment]
I've actually suggested a fix here: https://github.com/ozum/pg-structure/issues/64#issuecomment-727896841. If only there was a way to somehow override bundled types, I could have this fixed locally in my app.

**Comment by Qwerios** [comment]
You can always fork and install your forked version from github until it is fixed. Thats what I did for pg-structure at the time. If I had more free time I would have made a PR by now.

**Comment by jayarjo** [comment]
The problem gets terribly worse in TypeScript 4.

![Nov-17-2020 12-00-55](https://user-images.githubusercontent.com/150075/99362193-9d27c200-28cc-11eb-8d7d-e5f0ce7dc4d5.gif)

**Comment by ozum** [comment]
Hi, sorry for late. I'm overwhelmed nowadays. I will examine `pg-structure` and this library as soon as I have time. Although I'm not sure I can find a decent solution for types, because implementing this library with types is complicated.

First I'll try @jayarjo's solution.

**Comment by Qwerios** [comment]
@ozum I can relate to the overwhelmed feeling. If you can find the time it would be appreciated

**Comment by ozum** [comment]
Sorry for being so late and thanks for the patience.

With TypeScript 4, the problem is more complicated than I thought. I have to relax some of the types. `indexable-array` is meant to be a utility library for `pg-structure`. It's very hard to maintain typings fully compatible with base Array.

The current state is far from perfect, but I hope it fits its purpose. I'll update `pg-structure` with the new version of `indexable-array`. Please feel free to suggest.

**Comment by Qwerios** [comment]
I tend to shy away from extending core classes for exactly this reason. The use of Record<..> looks like a good solution to me. Don't have the time to get into all the details of your changes but the gist of it looks sane to me. Thanks for the update

**Comment by Qwerios** [comment]
I can confirm compilation works fine with TypeScript 4.1.3. I've removed my version pin and will close this issue.

**Comment by jayarjo** [comment]
Thanks for taking your time @ozum! I think your solution makes whole lotta sense.
